:doctype: book
:toc: left
:toclevels: 3
:toc-position: left
:numbered:

= Spring Boot Testsuite

== REST Service with Apache Tomcat

* Component : https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters/spring-boot-starter-web[Spring Boot Starter Web], https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters/spring-boot-starter-tomcat[Spring Boot Starter Web Tomcat]
* Framework : Spring Web, Spring Web MVC
* Container : Apache Tomcat

**Description**

A REST endpoint is exposed by Spring Boot using as Java Web Container Apache Tomcat. The REST endpoint `/greeting` returns a message to say hello world with an id which is increment
for each call.

----
http http://localhost:8080/greeting
HTTP/1.1 200 
Content-Type: application/json;charset=UTF-8
Date: Thu, 23 Feb 2017 08:11:08 GMT
Transfer-Encoding: chunked

{
    "content": "Hello, World!",
    "id": 1
}
----

== Access your data using JPA

* Component : https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters/spring-boot-starter-data-jpa[Spring Boot Starter Data JPA]
* Framework : Hibernate

**Description**

The goal of this use case is to setup a CRUD service talking to a H2 Database where the model is defined according to a https://github.com/redhat-microservices/lab_swarm-openshift/blob/master/solution/cdservice/src/main/java/org/cdservice/model/Catalog.java[CD Catalog entity].
At run time, an in memory H2 database is created, some records imported using an import.sql file. The definition of the datasource is defined within the `application.proerpties or application.yml` file.
A Service class will contain the CRUD methods. No transaction support is required.

References:

- https://spring.io/guides/gs/accessing-data-jpa[Spring How To guide]
- https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html[Spring Boot doc]
- http://blog.anthavio.net/2016/03/fun-with-spring-boot-auto-configuration.html[DataSource configuration]
